bootstrap_servers: "localhost:9092"
schema_registry_url: "http://localhost:8081"
# topic: "food_orders"
group_id: "my-group"
# use_schema_registry: true
key_avsc_paths:
  # - "confluent_kafka_utils/schemas/UserKey.avsc"
value_avsc_paths:
  # - "confluent_kafka_utils/schemas/Country.avsc"
  # - "confluent_kafka_utils/schemas/UserValue.avsc"
  - "confluent_kafka_utils/schemas/FoodValue.avsc"
topics:
  chicken_rice: "food_orders.chicken_rice"
  fish_soup: "food_orders.fish_soup"
  fast_food: "food_orders.fast_food"
