bootstrap_servers: "localhost:9092"
schema_registry_url: "http://localhost:8081"
topic: "topic1"
group_id: "my-group"
# use_schema_registry: true
key_avsc_path: "schemas/UserKey.avsc"
value_avsc_path: "schemas/User.avsc"
